// Generated by gencpp from file mypackage88/AddTwoInts.msg
// DO NOT EDIT!


#ifndef MYPACKAGE88_MESSAGE_ADDTWOINTS_H
#define MYPACKAGE88_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <mypackage88/AddTwoIntsRequest.h>
#include <mypackage88/AddTwoIntsResponse.h>


namespace mypackage88
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace mypackage88


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mypackage88::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::mypackage88::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::mypackage88::AddTwoInts > {
  static const char* value()
  {
    return "mypackage88/AddTwoInts";
  }

  static const char* value(const ::mypackage88::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::mypackage88::AddTwoIntsRequest> should match
// service_traits::MD5Sum< ::mypackage88::AddTwoInts >
template<>
struct MD5Sum< ::mypackage88::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mypackage88::AddTwoInts >::value();
  }
  static const char* value(const ::mypackage88::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mypackage88::AddTwoIntsRequest> should match
// service_traits::DataType< ::mypackage88::AddTwoInts >
template<>
struct DataType< ::mypackage88::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::mypackage88::AddTwoInts >::value();
  }
  static const char* value(const ::mypackage88::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mypackage88::AddTwoIntsResponse> should match
// service_traits::MD5Sum< ::mypackage88::AddTwoInts >
template<>
struct MD5Sum< ::mypackage88::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mypackage88::AddTwoInts >::value();
  }
  static const char* value(const ::mypackage88::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mypackage88::AddTwoIntsResponse> should match
// service_traits::DataType< ::mypackage88::AddTwoInts >
template<>
struct DataType< ::mypackage88::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::mypackage88::AddTwoInts >::value();
  }
  static const char* value(const ::mypackage88::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MYPACKAGE88_MESSAGE_ADDTWOINTS_H
