version: "3.8"
services:
  kinova_vs:
    container_name: nserc2025
    working_dir: /home/user/vs
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    network_mode: host
    tty: true
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - ../kinova_vs:/home/user/vs
      - /tmp/.X11-unix:/tmp/.X11-unixs