version: "3.8"
services:
  myservice88:
    container_name: mycontainer88
    working_dir: /home/user/myfolder88
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    network_mode: host
    tty: true
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - ../june_twentieth:/home/user/myfolder88
      - /tmp/.X11-unix:/tmp/.X11-unix
